server:
  port: 8085

logging:
  file:
    name: admin-service.log

dump:
  matcher-offers:
    db: matchingservice
    username: postgres
    password: root
    linuxFilePath: /opt/prod/
    windowsFilePath: ${user.home}\
